### ISSUE TITLE
macos 不可用，是要设定防火墙配置才能用吗

### ISSUE THREAD

**Issue by Ccheers** [zuiwuchang/v2ray-web#1]
希望可以出一份详细的说明

**Comment by zuiwuchang** [comment]
不可用是指什麼？程式無法運行還是代理無效，運行程式後可以打開web界面嗎？有任何的錯誤信息或截圖嗎？

我沒有 macos 所以只做了 windows 和 linux 的測試，不過用戶界面以web提供 macos 應該也可以正常運行才對，至少 v2ray 代理應該可以正常工作才對，全局代理的話默認是 linux下的iptable腳本，我不確定 macos 下的 防火牆是否和 iptables 一致不一致的話，全局代理可能需要你自己google下怎麼設置

**Comment by Ccheers** [comment]
明白了，我去查阅一下相关的代理文档，非常感谢
