### ISSUE TITLE
Has this project been updated?

### ISSUE THREAD

**Issue by liang-hiwin** [zuiwuchang/v2ray-web#11]

**Comment by zuiwuchang** [comment]
Yes! But because of CCP's retrograde, I'm busy looking for a job, so I don't have time to manage the open source project, but if v2ray has a major update or I have time to spare, I will continue to update this project

**Comment by thb007** [comment]
> Yes! But because of CCP's retrograde, I'm busy looking for a job, so I don't have time to manage the open source project, but if v2ray has a major update or I have time to spare, I will continue to update this project

ok
